### ISSUE TITLE
mintue round up on out going calls

### ISSUE THREAD

**Issue by flyaway3216** [felixb/callmeter#102]
maybe i've overlooked a setting that is already there, but is there a way/are you thinking to include an option where each call minutes are rounded up? this is how my uk talktalk account apparently counts up my used minutes ( ie a call or 10 seconds = 1 minute, 2:35 = 3 minutes...etc) and so i'm obviously going to get through my 100 minutes allowance quicker than this app would calculate. thanks for the good app though. looks great in every other way.

**Comment by felixb** [comment]
set your bill mode to 60/60.

https://github.com/felixb/callmeter/wiki/FAQ#what-are-these-bill-modes

**Comment by flyaway3216** [comment]
brilliant thanks, hadn't read that part of the instructions fully. my mistake. i was expecting it to be somewhere  in there as the app has most things covered. thanks again.
