### ISSUE TITLE
Take the opportunity to appoint a kind of currency in the settings.

### ISSUE THREAD

**Issue by Lifejazzy** [felixb/callmeter#103]
Take the opportunity to appoint a kind of currency in the settings. For the Ukrainian currency - hryvnia (грн.) (₴), but in the default settings, applications and unchangeable stand rubles  (руб.)( ₽) .
 Sorry for my bad English. 
![453dbece-d326-11e5-8a6d-9242ddc3e254](https://cloud.githubusercontent.com/assets/17225045/13033725/1f8a9c16-d32a-11e5-9985-4bdf4ae64ecb.png)

**Comment by felixb** [comment]
won't fix. it's just the hint, nothing critical.

**Comment by Lifejazzy** [comment]
You disrespectful communicate to the users of your program, six months is
not correct the error and then specify that you are and it is not going to fix
it. Support programs have not. it is unfriendly to the user.

2016-07-10 18:00 GMT+03:00 Felix Bechstein <notifications@github.com>:

**Comment by felixb** [comment]
well, this is still open source software written in my free time. i'm happy to merge a fix from yourself.

**Comment by Lifejazzy** [comment]
Hi.
Unfortunately I'm not a programmer, otherwise I would have gladly fixed it
all himself. It seems to me that to allow the user to select the type
of currency
in the drop-down list, or the ability to substitute itself not a difficult
task for the author of the program.


2016-07-10 18:24 GMT+03:00 Felix Bechstein <notifications@github.com>:

**Comment by Lifejazzy** [comment]
Hi. In the development of our dialogue, I might add. programa that is free,
but not quite. For example, I paid for it, and this is the confirmation.
Besides, in your interest to make the program better. They will appreciate
it all. who uses it.

Sincerely, Igor/

2016-07-11 8:08 GMT+03:00 lifejazzy <lifejazzy@gmail.com>:
