### ISSUE TITLE
No log singe CM 13

### ISSUE THREAD

**Issue by SebastianStotz** [felixb/callmeter#106]
Since installing CM 13 snapshot a few days ago, the log is not updated anymore (CM 12.1 worked well). I tried to give call meter all rights and deactivated all restrictions. Nothing helped.
Can you help?
Thank you

**Comment by felixb** [comment]
I'm running call meter on CM13 on a moto X 2014. It's running without any flaws.
Which version of the app are your running?

**Comment by SebastianStotz** [comment]
Hello Felix,
after uninstalling and a new installation it works now.
Thanks anyway...
You can close the topic now.
Sebastian
Am 12.04.2016 07:06 schrieb Felix Bechstein <notifications@github.com>:I'm running call meter on CM13 on a moto X 2014. It's running without any flaws.
Which version of the app are your running?
