### ISSUE TITLE
Feature request: include from calls

### ISSUE THREAD

**Issue by NEERAJ-YADAV** [felixb/callmeter#107]
Dear sir
There is an option in advance preference as "exclude from calls", which will exclude the numbers and will not take consideration effect of these numbers in the plan.
But sir , I have a minute plan and I want to consider the effect of one number(minutes will cut on that number and money will cut on others numbers) on my plan.
I call so many people, if I exclude then there will be a huge list and time consumption for creating that list by your option "exclude from calls".  Because I need the effect of one number.
Hence sir please make a option "only include from calls" so that I can include that number and see the effect of that numbers only.
Thank you sir....

**Comment by felixb** [comment]
Directly above the "exclude numbers" is a "include numbers" setting. This is what you want.

**Comment by NEERAJ-YADAV** [comment]
There is no "include number" setting above exclude number.
I am posting the screenshot. I am talking about preference then advance preferences then number groups.
![screenshot_2016-04-16-12-59-46](https://cloud.githubusercontent.com/assets/18465448/14579766/06d33d74-03d4-11e6-890e-f384fec62132.png)
![screenshot_2016-04-16-12-59-29](https://cloud.githubusercontent.com/assets/18465448/14579767/06d5db1a-03d4-11e6-9db8-ea2c15d1a191.png)

**Comment by felixb** [comment]
Well, you are viewing the definition of number groups. Just add another or change the name.
Check out the rules, there is a setting on how to interact with these groups.

**Comment by NEERAJ-YADAV** [comment]
Thanks..I have found the setting and I have done what I wanted. That has solved my problem.
Thanks.
