### ISSUE TITLE
Second SIM (Dual SIM) is logged as roaming while in its home country

### ISSUE THREAD

**Issue by 3ngin33r** [felixb/callmeter#109]
Thanks for a great app, really useful! I just have one issue which I'm hoping there is a solution to!

I have a dual SIM Huawei P8 Lite running Android 5.0.1.
The first SIM (id 0) is a UK number, which is correctly identified by Call Meter as roaming while in Switzerland and not roaming while in the UK. 
The second SIM (id 1) is a Swiss number, which is logged by Call Meter as "roaming" even when in Switzerland. When I export the logs to CSV, roaming = 1 for any SMS sent from the Swiss number to other Swiss phones within Switzerland (verified I wasn't roaming by looking at my phone account). 

If I go into Settings/About phone/Status/Network/SIM 1 it is shown as 'Roaming', SIM 2 is shown as 'Not Roaming'.

Not sure what the problem could be, but maybe Call Meter assumes the second SIM is roaming simply because the first SIM is roaming? Or Call Meter isn't able to read the 'Not Roaming' value of the second SIM?

**Comment by felixb** [comment]
I can't do anything about it. The android system is tracking the roaming state only for the whole system. So you'll get the state wrong for the second sim. :(
