### ISSUE TITLE
Data rounding

### ISSUE THREAD

**Issue by Eddict** [felixb/callmeter#110]
my provider rounds up data usage to MB's on a daily basis. so eg. a day usage of 3.25MB is rounded to 4MB at the end of the day.
my monthly total is now showing incorrectly due to this daily rounding/correction.
is this option somewhere available in the settings? 

regards Eddict

**Comment by felixb** [comment]
I'm sorry, but the current data layout does not allow such things.
I don't have time to do major redesign either.
