### ISSUE TITLE
Feature Request: common limit for more than one plan

### ISSUE THREAD

**Issue by gzech** [felixb/callmeter#111]
My provider gives me a monthly package of 100 minutes.
The minutes can be used for non roaming and also for roaming calls, but are billed different:
- when non roaming, calls in the package are free, calls outside the package cost 0,15
- when roaming, calls in the package cost 0,05, calls outside the package cost 0,20.

Both roaming and non roaming are counted in the same package.
So i have to count the used minutes in two different plans ( non roaming / roaming ), both using the same counter for decision in package / outside package.
So it would be necessary to have a common limit for two / more plans.

Suggestion: 
- implement ( similar to "NumberGroup", "HoursGroup" ) a "LimitGroup" or "Common Limits Group".
- implement in the plans a new limittype, "Common Limit", which selects one of the "Common Limits Group" / "LimitGroups".

Then both plans will increase the common minute package and can do the decision "in / out of package".
This would also help if a tariff has a package of "units", which can be used for SMS or calls and when minutes have different price than SMS.

**Comment by gzech** [comment]
This would also help if a tariff has a package of "units", which can be used for SMS or calls.

**Comment by felixb** [comment]
I think you can build such things already:

use three plans:

1. common plan with limit
2. non roaming plan w/o limit
3. roaming plan w/o limit

add rules as follows:

1. outgoing calls into 1. as long the limit is not reached
2. outgoing calls w/o roaming into 2.
3. outgoing calls w/ roadming into 3.

btw, there are already mixed plans supporting calls and messages at the same time.

**Comment by gzech** [comment]
Thanks for the info.
But i dont think it solves my problem:
It is fine when the limit is reached ( 2. and 3.).
But as long as the limit is not reached all calls go into common plan, no matter whether roaming or non roaming. In the plan i have only one field to set the cost, but the costs (in the limit)  are different for roaming / non roaming.

About the mixed plans: i missed the fact that i can set the costs separately for calls and SMS.

**Comment by felixb** [comment]
I'm not sure if it's working, but you can try to set up two plans, one for roaming, one w/o.
Then add a third plan that merges the first two plans. Add a limit in this third plan.
Set cost inside the first plans.

**Comment by gzech** [comment]
This works, thanks for the hint!
