### ISSUE TITLE
Export log to csv - numeric data in mixed, human readable formats (unreadable by spreadsheets, etc)

### ISSUE THREAD

**Issue by geekycow** [felixb/callmeter#113]
Hi

I've just tried to use the function to Export log to CSV to analyse data usage via a spreadsheet program.

The numbers for data usage exported to the log appear to be in rounded, mixed, human readable format (e.g. 802.3B, 12.78Mb, 13.03kb) making them pretty much unuseable on spreadsheets or other programs.  Shouldn't this kind of data be exported in a single, raw format (e.g. number of bytes?)

Warm Regards
Julie
x

**Comment by felixb** [comment]
this build includes unformatted amount/billed ammount.

http://ub0r.de/files/eeeb2a2875fc129dc9cc99b5fd25e1edc25fc26f-CallMeter3G-logRelease-3.11.11-4-gaf64753.apk
