### ISSUE TITLE
feature request: distinguish between in-country call and foreign countries

### ISSUE THREAD

**Issue by mgrn0** [felixb/callmeter#115]
Since there are a couple of plans available which offer different contingents of talking minuts for in-country calls and other contingents for calls to other countries it would be nice if we could set a filter ('country prefix' or similar) for the widgets. Does this sound plausible? Attached is a screenshot from my phone plan overview, it would be nice if callmeter widgets could recreate this overview on the phone:
![screenshot 2016-06-30 at 14 15 52 pm](https://cloud.githubusercontent.com/assets/3019226/16487793/361e7862-3ecd-11e6-971b-051a160c6d90.png)

**Comment by felixb** [comment]
That is already possible by using a few number groups. Just create the groups according to your needs and put all the international prefixes in there. E.g. `+49%` for calls to Germany, `+1%` for calls to USA.

**Comment by mgrn0** [comment]
awesome, thanks for the clarification!
