### ISSUE TITLE
can't enter '%'  in advanced pref/numbers group

### ISSUE THREAD

**Issue by voyteke** [felixb/callmeter#119]
just trying to setup a new old phone with CM 3.11.11

when trying to enter a number in advanced pref/numbers group like say +66%, % gets stripped, and, a name from phone book appears with +66 / Auser Name
presumedly first user starting with +66 ?

I vaguely recall seeing similar issue long time ago ?

Nexus 5 / Euclidean 20170212 / A 7.1.1 5th Feb 2017 / kernel 3.4.0

**Comment by felixb** [comment]
I can not reproduce this bug. This is how I tried:

1. open any number group
2. select `+` to add a number
3. enter `+49%` or `+66%` in the text field. verified with both.
4. select `ok` to add it to the list

as expected, the `+49%`/`+66%` is added to the list of numbers. nothing got striped, no user name is shown.

**Comment by voyteke** [comment]
Felix, thanks.
I'm really puzzled:
Went to number group where I had a 'failed entry' with +66 and a phone book name of a contact, deleted that entry.
Created a new entry, saved, hmmm, correct, saved as expected.

Don't know... that phone occasionally has 'stuck keyboard key' issue, maybe that's what happened?
But it was pulling a name from contacts...?

Anyhow, sorry, don't know what happened, thanks for testing.
Thanks for a great app.
B
