### ISSUE TITLE
Cannot write Log Files to SD or elsewhere

### ISSUE THREAD

**Issue by Isengo1989** [felixb/callmeter#120]
"Fehler beim schreiben der Exportdatei" - "Error when writing the export file"

Is this Error Message known? A solution on hand maybe? I am using Android 6.0 with an Huawei P9Lite

**Comment by felixb** [comment]
please try giving the app permission to write the file in androids preferences for this app.
I guess, there is something messed up with runtime permissions.

**Comment by aput** [comment]
@Isengo1989, did you ever solve this?
I have the same problem for many weeks (started around time you reported this). 

@felixb, how to give that permission? Checked my device (Samsung S3 Neo on Android 4.2.2) but cannot find it.

Thanks, Andre
