### ISSUE TITLE
Dual SIM-id not work

### ISSUE THREAD

**Issue by slashxl** [felixb/callmeter#122]
Hi, I have now a new SIM Card and since that time, the SIM-id doesn't work anymore for callings.

**Comment by slashxl** [comment]
![2017-07-25 23 11 03](http://rupp-info.de/Screenshot_1.png)
![2017-07-25 23 11 03](http://rupp-info.de/Screenshot_2.png)

**Comment by slashxl** [comment]
Can you help me?

**Comment by felixb** [comment]
That is strange indeed. You did not change your phone, right?

**Comment by slashxl** [comment]
Yes, it's the same phone, but now I have try it with the old SIM Card once again. Unfortunately is it now the same problem with any SIM. 
Not a hunch...

**Comment by meiser79** [comment]
After updating from LineageOS 13.0 (Android 6.0.1) to LineageOS 14.1 (Android 7.1.2), the SIM id is also missing here.

**Comment by felixb** [comment]
I'm pretty sure the the current update in #124 fixes the issue.
Please follow https://github.com/felixb/callmeter/issues/124#issuecomment-343750019 and try the current build.

**Comment by slashxl** [comment]
Hi, wow great job!

Thank you
