### ISSUE TITLE
Two SIM slots shown and counted on, while only one is existing

### ISSUE THREAD

**Issue by bmwdroid** [felixb/callmeter#123]
On my LG G5 (H850 stock ROM) calls are counted on slot 2, while SMS are counted on slot 1.
But the device has only one SIM slot. 
Doesn't really bother me, as long everything is counted correctly, but it's a bit confusing. 
Thx for the App anyhow.

**Comment by felixb** [comment]
should be fixed in upcoming version when re-importing the default rule set.
