### ISSUE TITLE
More period length options?

### ISSUE THREAD

**Issue by voyteke** [felixb/callmeter#127]
Thanks for CM, great app.
My plan now gives me 42 days, in place of, 28 days (depending on recharge amount), there is no way to enter 42 days (or 6 weeks) as far as I can tell.

**Comment by felixb** [comment]
Hey. I'm not actively developing this app anymore. Google forced me from removing it from Play Store.

**Comment by voyteke** [comment]
felix
thanks for reply. yes, I more or less doubted if it is still 'under active development', and, suspected it's not... 
oh well...
really nice app, admittedly, as my carrier now gives me more usage that I can use, I no longer need it as much as I've had in the past..
though, it's still very handy for my overseas calls, I've entered new o/s rates, and, I use CM for checking how much can I call o/s from credit I get.
anyhow, thanks again, voytek
