### ISSUE TITLE
When using "SwitchMe" logs are not combined

### ISSUE THREAD

**Issue by mvidelgauz** [felixb/callmeter#51]
On my device with [SwitchMe](https://play.google.com/store/apps/details?id=fahrbot.apps.switchme&hl=en) installed usage statistics from different accounts are not combined.
It will be nice to sum all usage up and show (use for warning, etc.) combined result since mobile provider counts minutes/messages/megabytes independently on currently active account )))

**Comment by mvidelgauz** [comment]
Thank you for this answer. The reason of not hacking native account separation is more than satisfactory.
Still, if you could add a feature of export/import current logs to/from external SD/cloud storage than that could be a good workaround not only for the case I described. Also people sometimes move their SIM cards from one phone to another in the middle of billing period....

Thanks again for great application!

**Comment by felixb** [comment]
In fact, Call Meter 3G has a feature to export/import logs.

**Comment by mvidelgauz** [comment]
Thanks! Probably I overlooked this feature, will now check...

Thanks!

**Comment by mvidelgauz** [comment]
Found it. Small issue - exporting was easy to find. Importing is under "Import rule set" title, but inside there is option to import logs...
