### ISSUE TITLE
plan

### ISSUE THREAD

**Issue by ramnikbhai** [felixb/callmeter#56]
I have plan in which 2000 min free in same circle for all lacal call
After limit charges are
1 same nate work mob .2
2 other network mon .3
3 on land line  .5
How to set plan

**Comment by felixb** [comment]
you basically need 4 plans:

1. free calls, limit 2000
2. network calls, cost as you said
3. landline calls, cost as you said
4. other calls, cost as you said

then you need following rules in that particular order:

1. any outgoing call, only if limit is not reached -> plan 1
2. out. calls matching your networks prefix -> plan 2
3. out. calls matching landline prefix -> plan 3
4. out. calls -> plan 4
