### ISSUE TITLE
lot of space status screen

### ISSUE THREAD

**Issue by csabi23** [felixb/callmeter#60]
I make a tariff but my tariff name long. The software add lot of space status screen. I attached some picture.
![shot_2015-03-17_11-32-17](https://cloud.githubusercontent.com/assets/3310658/6685511/d26522c6-cc9a-11e4-9d8b-c3bd23a5a58d.png)
![shot_2015-03-17_11-31-51](https://cloud.githubusercontent.com/assets/3310658/6685510/d25d210c-cc9a-11e4-9ac5-bcc40b15db65.png)
![shot_2015-03-17_11-32-07](https://cloud.githubusercontent.com/assets/3310658/6685512/d265add6-cc9a-11e4-86c5-2ca5f24c8d43.png)

**Comment by felixb** [comment]
please just reduce the length of the labels.
