### ISSUE TITLE
exclude apps from data plan

### ISSUE THREAD

**Issue by gizmo9002** [felixb/callmeter#64]
Hello there!

As more and more companies offer unlimited streaming or browsing through specific applications, it would be nice to be able to exclude those apps from the data plan.

Would something like that be possible? Thanks in advance!

Cheers,
Theodore

**Comment by felixb** [comment]
the android API exposes date usage on linux kernel layer. i'm not able to distinguish between apps.
even if it is possible, the number of necessary data logs would rise to an unhandlable number.
