### ISSUE TITLE
Call Meter 3G could be causing incoming SMS messages are not shown by messaging apps

### ISSUE THREAD

**Issue by aamadorj** [felixb/callmeter#66]
After updating my Nexus 5 to Android 5.1.1 the incoming SMS messages were not shown by messaging apps. I captured some logs and the ROM dev analyzed them but he didn't find anything anormal.

So I started to uninstall all my apps related to messaging and I found Call Meter 3G was the one causing the issue.

**Comment by felixb** [comment]
what is your default messaging app? hangouts? mms?

i could not reproduce this issue on my device running android 5.1.1.

**Comment by aamadorj** [comment]
I'm sorry for the delay providing the info you requested. I'm been very busy at work and family matters. 

At first, my N5 was using YAATA as default SMS messaging app. After I discovered the issue I described, I uninstalled YAATA and I tried with Hangouts. The issue remain. 

After I asked OptiPop ROM developer, I tried with a full wipe and I restored all non system apps with Titanium Backup. The issue showed again. So, I tried a full wipe and then I did some tests with only system apps installed. Hangouts was able to receive SMS perfectly. After this success, I restored all other apps and I found the issue was back. 

Finally, I did a full wipe again, recheck I was able to receive SMS using Hangouts and then I restored each of the other apps, one by one, while I tested SMS were being received. I restored all apps but CallMeter 3G. As I was receiving SMS without issues, even using again YAATA as default messaging app, I thought CallMeter was causing the issue. 

Do you think restoring CallMeter 3G from a TB backup could cause the issue? 

I have some logcats of some of my tests saved somewhere, but none of them showed anything unusual according to OptiPop dev. I'll look for them in case you think they could be useful.

**Comment by felixb** [comment]
Well, I still can't think of why this should happen.
Please install this debug version of the app and send your logs.

http://ub0r.de/files/fc346b9d3dbbe00dbc8464927843547af52b640f-CallMeter3G-logRelease-3.11.7-4-g1a93027.apk

**Comment by aamadorj** [comment]
I've been quite busy at work, so I haven't had the chance to do further tests. But today i decided to make a full backup and then I installed Call Meter 3G from Google Play. Once it was installed I sent several SMS to myself and I received all. 

I don't know what went wrong before. All I know is I'm happy the problem is gone. Thanks for your time and interest in this issue.

**Comment by felixb** [comment]
alright. thanks for the heads up.
