### ISSUE TITLE
Calculate Call In during roaming in minutes 60/60

### ISSUE THREAD

**Issue by narangrajesh** [felixb/callmeter#68]
Whese to config setting for calls in during roaming because incoming calls have charged during roaming.

**Comment by felixb** [comment]
I sadly don't known, what your problem is.
Please try to rephrase with different words.

**Comment by narangrajesh** [comment]
Hello,
Actually, I want to track record of minutes consumed in incoming call during roaming. 1 minute pulse is applicable on my plan.





        Sent by Outlook for Android





On Tue, May 5, 2015 at 9:32 PM -0700, "Felix Bechstein" <notifications@github.com> wrote:
I sadly don't known, what your problem is.
Please try to rephrase with different words.

---

**Comment by felixb** [comment]
well, you just need need to set the bill mode to 60/60 for your roaming plans.
