### ISSUE TITLE
All calls and SMS assigned to SIM1 in dual sim phone

### ISSUE THREAD

**Issue by ArcziF** [felixb/callmeter#71]
Call Meter 3G (v3.11.7) used on Samsung S5 Mini Duos does count all calls and SMS from both SIM cards together and classifies them as SIM1.

"Calls In/Out 2" and "SMS In/Out 2" are always showing 0.

Phone logs (build in) show a small icon indicating 1st or 2nd SIM card properly. Call Meter 3G seems to not use this info.

To reproduce a bug:
1. Install Call Meter 3G on S5 Mini Duos with 2 SIM cards
2. Call & text from both cards
3. Check logs of Call Meter 3G

**Comment by ArcziF** [comment]
Hi Felix. I sent you the logs.

**Comment by felixb** [comment]
do you see the "sim id" field in the logs view (swipe right).
are the ids matching your sims?

**Comment by ArcziF** [comment]
Yes, logs of Call Meter 3G show both sims separately and each call/sms match the used sim correcly. They are numbered 0 and 1 in logs of Call Meter.

![logs_screenshot](https://cloud.githubusercontent.com/assets/12664499/8023466/d83129bc-0d0d-11e5-9f66-cbadb7941a16.png)

![summmary_screenshot](https://cloud.githubusercontent.com/assets/12664499/8023467/d8349296-0d0d-11e5-9bd2-790b57851bd1.png)

**Comment by ArcziF** [comment]
Now I noticed another, related issue. First SIM is configured to have billing method 60/60s. Second SIM is configured to bill 1/1s. As you can see on the screenshot above, calls from both are rounded to full minutes, what means, that settings of the first SIM are applied to both SIMs.

**Comment by felixb** [comment]
It is a configuration issue.
You need to update the rules matching logs into the sms/calls plans.
Please recheck the sim id setting for your rules "sms/calls out sim 2". I guess you have stated a wrong sim id there.
