### ISSUE TITLE
Enhancement to have multiple data plans

### ISSUE THREAD

**Issue by besho82** [felixb/callmeter#73]
in UAE, and i am sure in other countries too, there are different data plans. you have a social data and normal data. for example. i have 1 GB monthly social data (WhatsApp, Facebook, BBM & Twitter) and 400 MB monthly for all other data.

is there a way that we can have 2 data plans, and the same way that we select a number list to select a list of apps that the data of those apps is calculated separately.

**Comment by felixb** [comment]
It is sadly not possible with the way traffic stats are working in Android.
