### ISSUE TITLE
single time (non-periodic) plan

### ISSUE THREAD

**Issue by neobesseya** [felixb/callmeter#74]
is there a way to add a plan which is available to certain numbers for just one limited time interval?
I can add all parameters, except that the time is not periodic.  If i add the plan, the program assumes it is periodic and was valid already in the previous month.  I did not find a way to avoid this.
"Billing period" is the only way i found to add start date and duration, but then it is automatically a periodic time.

cheers, Neo.

**Comment by felixb** [comment]
it's a valid requirement, but i think, i'll never manage to build it.
it just takes to much time to build these kind of heavy changes in data structure which are needed to implement it.
