### ISSUE TITLE
No option for sim id in HTC one dual sim 802d.

### ISSUE THREAD

**Issue by anubandh** [felixb/callmeter#77]
As the title suggests the call meter 3g v. 3.11.7 does not show the option for sim id in rule set for calls. The most weired part is the app shows the option of sim id in sms rule which certainly means that it can detect the dual sim functionality.
plz. sort the issue in next update.
i am on android 5.02 with official htc rom and rooted with twrp recovery installed.

**Comment by felixb** [comment]
this build should fix the issue: http://ub0r.de/files/3f965444be2a04eb4cdc522667a7f76bae0549d0-CallMeter3G-logRelease-3.11.8-1-g577b2f9.apk

please verify.

**Comment by anubandh** [comment]
Yes today after recieving the update, the issue is fixed, Thanks for all the hard work.
