### ISSUE TITLE
Feedback link from the app takes the user to Googlecode page

### ISSUE THREAD

**Issue by abhijeetbhanjadeo** [felixb/callmeter#78]
Hi Felixb,

I tried using the feedback link from the app, it redirects me to Google code page  https://code.google.com/p/callmeter/issues/list where I'm informed that code support has been moved to github.

Can you please link the feedback directly to Github?

Thanks,
Abhijeet

**Comment by felixb** [comment]
i could not find any leftover in the source code.
which app version and language are you using?

**Comment by abhijeetbhanjadeo** [comment]
Hi Felixb,

I'm using Call Meter NG v2.3.21 and language is English. Just checked it now, it seems to be working properly now, it's redirecting to GitHub page.

Thanks,
Abhijeet
