### ISSUE TITLE
Limit on Calls and SMS

### ISSUE THREAD

**Issue by all-gitty** [felixb/callmeter#81]
I could use a limit entry for both calls and SMS, like is already available for data. My plan is a limited plan on calls and SMS too, not just data.

**Comment by felixb** [comment]
just set up the limit for the plan to whatever you like.

1. long-click the plan
2. set limit

**Comment by all-gitty** [comment]
On my particular older model phone, VM670, when I long-click the plan the function doesn't seem to work correctly.  What appears until I release the long-click is a very thin bar along the right edge of the screen--somewhat like a coin in thickness line like at the edge of the screen and there may be more hidden out from the edge of the line off-screen.

**Comment by felixb** [comment]
Try opening settings and navigate to plans. Select your plan and edit it.
