### ISSUE TITLE
Unable to pull in android studio

### ISSUE THREAD

**Issue by xerosanyam** [felixb/callmeter#84]
Error:(16, 0) Gradle DSL method not found: 'play()'
Possible causes:<ul><li>The project 'callmeter-master' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by felixb** [comment]
it's working for me without any flaws. did you try to compile it from coommand line with the gradle wrapper?
you should be able to create the wrapper by running gradle wrapper'.
