### ISSUE TITLE
Ads cover entire screen

### ISSUE THREAD

**Issue by Dorus** [felixb/callmeter#85]
I clicked 'got it' at the bottom where it told me it uses devices id. Now the ads suddenly cover the entire screen. When I close call meter, I can see the normal stats for five seconds before the ads load and cover the screen again. 

(covering the entire screen means one small add on top and the rest of my screen empty )

**Comment by felixb** [comment]
thanks for the notice and please excuse the inconvenience.
this build should fix the problem:

http://ub0r.de/files/3586605ad7caedb5518d750ce58cfcaeb8db3d00-app-release.apk

**Comment by Dorus** [comment]
Confirmed fixed.
