### ISSUE TITLE
copy rules or tariff

### ISSUE THREAD

**Issue by csabi23** [felixb/callmeter#87]
Dear sir, how to copy the rules because new rules no change lot of. If I change only one I make a new rules lot of things not one. Please help. Thank you.

**Comment by felixb** [comment]
I'm sorry, but I really do not understand your needs.
Please try again with different words.

**Comment by csabi23** [comment]
How to copy one new rule to old rule change a little?

**Comment by csabi23** [comment]
And How to copy one new rate to old rate change a little?

**Comment by csabi23** [comment]
Is it  understand?

**Comment by felixb** [comment]
you can not copy rules in the app.
the only way to do it is exporting the rule set as xml file, edit it by hand and import it again.
