### ISSUE TITLE
Crash when editing rule

### ISSUE THREAD

**Issue by rytier** [felixb/callmeter#91]
Hi,
I have Sony Z3 Compact (D5803) Android 5.1.1.
When I pick a Call rule, choose Edit and scroll down, the last item I see is "Is SIP call" .  After that the system says app crashed and app reloads the list of rules. Similar stuff happens with SMS rules (last item shown is "Is Websms") and MMS rules (editing doesn't start, app goes back to Preferences). This prevents me from editing stuff like include/exclude groups for the rules... unless I learn how to edit config file by hand :)

(edit: exchanged sentence order to improve readability)

**Comment by felixb** [comment]
Which version of the app are you running? I fixed a similar bug with one of the latest versions. 
Do you know, how to send logs from that crash?

**Comment by rytier** [comment]
App version is 3.11.9.1
I saw the bug #70 now, it may be a similar issue.
Not sure how to send logs, but willing to learn :) need to install something?

-- MK 

---- Felix Bechstein wrote ----

**Comment by felixb** [comment]
you may install [this build](http://ub0r.de/files/64981ce880faf8177d28867aaf907cc181e02327-CallMeter3G-logRelease-3.11.9.1-2-g59d0493.apk), crash the app, open it again, and send logs from within the settings.

**Comment by rytier** [comment]
Done. Crashed twice - once for call rule, once for MMS rule. 

-- MK 

---- Felix Bechstein wrote ----

**Comment by felixb** [comment]
the bug was introduced again by switching to crowdin as translation platform..

this build works for me though:
http://ub0r.de/files/d7565346d8edc80066528e7bcc7db3549588b02c-CallMeter3G-logRelease-3.11.9.1-4-g4efe609.apk

**Comment by rytier** [comment]
Yes, that build works for me as well.
Many thanks for making it work again.
