### ISSUE TITLE
Data not recognized

### ISSUE THREAD

**Issue by Micha-Btz** [felixb/callmeter#94]
i there,

i use this https://felixb.github.io/callmeter/rulesets/Germany_WinSIM_LTE_Mini_Plus_2000.xml
ruleset, but only SMS ands Calls are recognized. I add some screen shots
![screenshot_2015-10-29-11-50-29](https://cloud.githubusercontent.com/assets/4420944/10869469/19b6ed6a-80b1-11e5-862a-10df247255f6.png)
![screenshot_2015-10-29-11-50-48](https://cloud.githubusercontent.com/assets/4420944/10869470/19b8e854-80b1-11e5-8e81-8f3609f875f9.png)

. Sony Xperia Z 1 Compact CM12.1. 
Some hints to solve this?

Micha

**Comment by felixb** [comment]
looks like the rule set has a broken/missing rule for data stats.
just add a new rule for data matching any data logs into the existing data plan.

please export the rule pointing to this issue. i'd like to replace the broken rule set with your fixed version.

**Comment by Micha-Btz** [comment]
I have created that rule and tested it for a month now. working fine. i will attach this config.
or should i create a PR?

[Germany_WinSim_LTE_Mini_Plus_2000.zip](https://github.com/felixb/callmeter/files/53551/Germany_WinSim_LTE_Mini_Plus_2000.zip)

**Comment by felixb** [comment]
I just uploaded it myself. I've a script for that. :)
Thanks for the contribution.
