### ISSUE TITLE
Update on F-Droid

### ISSUE THREAD

**Issue by mvdan** [felixb/callmeter#95]
Hi! I work on F-Droid and I'm trying to update your app there, but there are a few blockers:

* You use play-services, which is non-free. If you made it optional like with a flavour, then we could build the foss flavour. Example gradle file: [PassAndroid](https://github.com/ligi/PassAndroid/blob/master/android/build.gradle)
* You use third party maven repos (the `githubusercontent` urls). Are they really necessary? Isn't mavenCentral/jcenter or even jitpack enough?
* Your version name and code are generated, so we can't pick them up automatically to detect when the app is out of date.

**Comment by felixb** [comment]
well, this is an open source project, feel free to send in PRs.

1. just send a PR for creating a flavor w/o any google stuff
2. i just don't want to manage another account. it doesn't harm anything.
3. the version codes are derived from git tags, you should be able to use that, right?

I'll close this issue, which does not mean I don't want to deal with it. Please send PRs and we'll discuss on the individual changes.

**Comment by IzzySoft** [comment]
Felix, would you consider releasing the `.apk` along with the `/releases` (i.e. attach it to the tags when released)? That wouldn't require any changes to your code (not being a programmer, I couldn't provide a PR anyway), but I then could pick it up automatically and include it with [my F-Droid compatible repo](https://android.izzysoft.de/repo), each new release automatically being updated within (usually) 24h. Deal?

**Comment by felixb** [comment]
well, i try to remember that.

**Comment by IzzySoft** [comment]
Would be great! If you could already attach the recent version's `.apk` to its tag (3.11.13), I can set it up to fetch future versions (I need an initial version for that). Otherwise a "ping" would be nice when you started ;)

**Comment by felixb** [comment]
done.

**Comment by IzzySoft** [comment]
Thanks, Felix! You can now find it [here](https://apt.izzysoft.de/fdroid/index/apk/de.ub0r.android.callmeter) for users with the F-Droid client to install/update it from.
