### ISSUE TITLE
Version 3.11.10 doesn't work on Samsung Galaxy Pocket

### ISSUE THREAD

**Issue by Antonio73** [felixb/callmeter#96]
version 3.11.10 doesn't work on Samsung GT-S5300 (Galaxy Pocket) android version 2.3.6

**Comment by felixb** [comment]
You should at least tell me, what's not working. 
I can't fix "does not work".

**Comment by felixb** [comment]
please check out this build and verify.

http://ub0r.de/files/f6d01205caa6a0af2131e664d47bf5e2d49d9fb2-CallMeter3G-logRelease-3.11.10-2-gacd0cfb.apk
