### ISSUE TITLE
Calls total cost not calculated correctly

### ISSUE THREAD

**Issue by apwood** [felixb/callmeter#97]
I have set up Call Meter NG on my Galaxy S4 (on Android Lollipop) with a simple single plan.  Calls cost 0.03 per 60 second increment, so a 1 second call costs 0.03 a 1 minute call costs 0.03 and a 1 minute 1 second call costs 0.06.  I set the billing mode as 60/60, with a per call cost of zero, and a per minute cost of 3p and no free calls.

Since the date I set this up I have made 5 calls each under 60 seconds, and one which was 2 minutes 6 seconds.  The total cost is therefore 5x0.03 + -0.09 = 24p

Call Minder NG displays:
Out 0.19£ ¦ 6:13 (6) ¦ 3:06

Since calls are billed at £0.03 per minute (60s) then the total cost cannot be £0.19 - it has to be a multiple of £0.03 !

**Comment by felixb** [comment]
I deprecated this app ~5y ago. I guess you have to reset stats to pull in the new settings for calls you have done in the past. 
You should migrate over to Call Meter 3G, it's the successor and handles these cases automatically.
